#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDD_OPTIONS                             100
#define IDB_ICON                                110
#define IDB_SWITCH_LANG                         111
#define IDB_SWITCH_SETTING                      112
#define IDC_CHECK_OSD                           1000
#define IDC_EDIT_CAPFOLDER                      1001
#define IDC_CAPFOLDER_BROWSE                    1002
#define IDC_COMBO_SETTINGS                      1003
#define IDC_SETTINGS_ADD                        1004
#define IDC_SETTINGS_DELETE                     1005
#define IDC_CHECK_SETTINGS_TEST                 1006
#define IDC_COMBO_FACE                          1007
#define IDC_COMBO_GAIJI_FACE                    1008
#define IDC_COMBO_GAIJI_TABLE                   1009
#define IDC_COMBO_METHOD                        1010
#define IDC_CHECK_CAPTION                       1011
#define IDC_CHECK_SUPERIMPOSE                   1012
#define IDC_EDIT_DELAY                          1013
#define IDC_CHECK_IGNORE_PTS                    1014
#define IDC_CHECK_TEXTOPA                       1015
#define IDC_CHECK_BACKOPA                       1016
#define IDC_EDIT_TEXTOPA                        1017
#define IDC_EDIT_BACKOPA                        1018
#define IDC_EDIT_ADJUST_X                       1019
#define IDC_EDIT_ADJUST_Y                       1020
#define IDC_EDIT_ADJUST_SIZE                    1021
#define IDC_EDIT_ADJUST_RATIO                   1022
#define IDC_EDIT_STROKE_WIDTH                   1023
#define IDC_CHECK_STROKE_WIDTH                  1024
#define IDC_COMBO_STROKE_LEVEL                  1025
#define IDC_EDIT_BY_DILATE                      1026
#define IDC_EDIT_VERT_ANTI                      1027
#define IDC_CHECK_ADD_PADDING                   1028
#define IDC_CHECK_IGNORE_SMALL                  1029
#define IDC_CHECK_CENTERING                     1030
#define IDC_CHECK_ROMSOUND                      1031
#define IDC_STATIC_CAPFOLDER                    1032
#define IDC_STATIC_GAIJI_TABLE                  1033
#define IDC_EDIT_ADJUST_VIEW_X                  1034
#define IDC_EDIT_ADJUST_VIEW_Y                  1035
#define IDC_CHECK_SHRINK_SD_SCALE               1036
#define IDC_COMBO_AVOID_HALF                    1037
